/**
 * DTZ Official HQ - Advanced Multi-Admin Relay & Document Engine
 * Version: 10.5.0 (Enterprise)
 * Developers: Raviya, Shagiya, Ashiya
 */

const ADMIN_NUMBERS = [
    "94763036217",
    "94778430626",
    "94741856766",
    "94788262515"
];

// Matrix Background Initialization
function initMatrix() {
    const canvas = document.getElementById('matrix-canvas');
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*ｦｱｳｴｵｶｷｸｹ";
    const fontSize = 16;
    const columns = Math.floor(canvas.width / fontSize);
    const drops = Array(columns).fill(1);

    function draw() {
        ctx.fillStyle = "rgba(0, 0, 0, 0.05)";
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.fillStyle = "#00ffcc";
        ctx.font = fontSize + "px 'Share Tech Mono'";

        for (let i = 0; i < drops.length; i++) {
            const text = chars[Math.floor(Math.random() * chars.length)];
            ctx.fillText(text, i * fontSize, drops[i] * fontSize);
            if (drops[i] * fontSize > canvas.height && Math.random() > 0.975) drops[i] = 0;
            drops[i]++;
        }
    }
    setInterval(draw, 35);
}

// Advanced Terminal Output Helper
async function printToTerminal(text, delay = 400) {
    const out = document.getElementById('t-output');
    const p = document.createElement('p');
    p.innerHTML = text; // HTML enabled for colors/bold
    out.appendChild(p);
    window.scrollTo(0, document.body.scrollHeight);
    await new Promise(r => setTimeout(r, delay));
}

// Loading Bar Simulation
async function showProgressBar(duration) {
    const out = document.getElementById('t-output');
    const progress = document.createElement('p');
    out.appendChild(progress);
    const steps = 20;
    for (let i = 0; i <= steps; i++) {
        let bar = "[" + "=".repeat(i) + " ".repeat(steps - i) + "]";
        progress.textContent = `> COMPILING: ${bar} ${Math.round((i / steps) * 100)}%`;
        await new Promise(r => setTimeout(r, duration / steps));
    }
}

// System Boot Sequence
async function boot() {
    const welcome = document.getElementById('welcome');
    if(welcome) welcome.classList.add('slide-out');
    
    const term = document.getElementById('terminal');
    term.style.display = 'flex';
    
    await printToTerminal("<span style='color:#fff'>[SYSTEM]</span> INITIALIZING DTZ KERNEL v10.5...");
    await printToTerminal("> LOADING SECURITY_PROTOCOLS...");
    await showProgressBar(1000);
    await printToTerminal("> SYNCING ADMIN_RELAY_NETWORK (4 NODES FOUND)...");
    await printToTerminal("> RAVIYA, SHAGIYA, ASHIYA MODULES ONLINE.");
    await printToTerminal("<span style='color:#00ffcc'>[SUCCESS]</span> SECURE CHANNEL ESTABLISHED.");

    setTimeout(() => {
        term.style.display = 'none';
        document.getElementById('portal').classList.add('fade-in');
        document.body.style.overflow = "auto";
    }, 800);
}

// PDF Document Generation Engine
async function generatePDF(data) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    // Background and Header
    doc.setFillColor(10, 10, 10);
    doc.rect(0, 0, 210, 297, 'F');
    doc.setTextColor(0, 255, 204);
    doc.setFont("courier", "bold");
    doc.setFontSize(22);
    doc.text("DTZ RECRUITMENT HQ - INTEL REPORT", 20, 30);
    
    // Body Text
    doc.setFontSize(14);
    doc.setTextColor(255, 255, 255);
    doc.text(`CODENAME: ${data.name.toUpperCase()}`, 20, 60);
    doc.text(`LOCATION: ${data.city}`, 20, 75);
    doc.text(`AGE: ${data.age}`, 20, 90);
    doc.text(`CONTACT: ${data.whatsapp}`, 20, 105);
    doc.text(`EXP: ${data.exp}`, 20, 120);
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by DTZ Secure Relay System | Dev: Raviya, Shagiya, Ashiya`, 20, 280);
    
    // Save to device
    doc.save(`DTZ_REPORT_${data.name.replace(/\s+/g, '_')}.pdf`);
}

// Form Submission & Admin Relay
document.getElementById('dtzForm').addEventListener('submit', async (e) => {
    e.preventDefault();
    
    const formData = {
        name: document.getElementById('name').value,
        city: document.getElementById('city').value,
        age: document.getElementById('age').value,
        whatsapp: document.getElementById('whatsapp').value,
        exp: document.getElementById('exp').value
    };

    // UI Feedback
    const term = document.getElementById('terminal');
    const out = document.getElementById('t-output');
    out.innerHTML = ""; // Clear old logs
    term.style.display = 'flex';

    await printToTerminal("> ENCRYPTING INTEL PACKET...");
    await showProgressBar(1200);
    
    await printToTerminal("> GENERATING SECURE PDF DOCUMENT...");
    await generatePDF(formData);
    
    // Admin Selection: Balanced Round-Robin or Random
    const randomAdmin = ADMIN_NUMBERS[Math.floor(Math.random() * ADMIN_NUMBERS.length)];
    await printToTerminal(`> ASSIGNING CASE TO ADMIN_NODE: [${randomAdmin}]`);

    const msg = `*🛡️ DTZ RECRUITMENT INTEL 🛡️*%0A` +
                `--------------------------%0A` +
                `👤 *CODENAME:* ${formData.name.toUpperCase()}%0A` +
                `📍 *LOCATION:* ${formData.city}%0A` +
                `🎂 *AGE:* ${formData.age}%0A` +
                `📱 *WHATSAPP:* ${formData.whatsapp}%0A` +
                `💻 *EXPERIENCE:* ${formData.exp}%0A` +
                `--------------------------%0A` +
                `⚠️ *ACTION:* PDF Generated Successfully.%0A` +
                `*Please attach the downloaded PDF and the 4 photos now.*%0A` +
                `--------------------------%0A` +
                `_Relay System Verified_`;

    await printToTerminal("<span style='color:#ffff00'>> REDIRECTING TO WHATSAPP HQ...</span>", 1500); 
    window.location.href = `https://wa.me/${randomAdmin}?text=${msg}`;
});

window.onload = () => {
    initMatrix();
    // Only call boot() if you have a welcome screen, or call it directly.
    boot(); 
};

window.addEventListener('resize', () => {
    const canvas = document.getElementById('matrix-canvas');
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
});